name = "proxgrp"
main = "_worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

# ✅ ဒီ line ကို ထည့်ပါ
keep_vars = true

[vars]
#UUID = ""
WS_PATH = "galaxy-tunnel"
PROXYIP = "bunny.net"
DNS_RESOLVER_URL = "https://1.1.1.1-dns.com/dns-query"
